### ISSUE TITLE
A question about S7.sln

### ISSUE THREAD

**Issue by Mallowan** [killnine/s7netplus#103]
Hello everyone,
Could someone explain where did all these files (highlighted) come?
In what way was it done?
I'm asking that because I did some test, I created new solution on other PC, then added all highlighted files and managed to read/write Boolean, Real and Word. That's working. I used PLCSIM and NetToPLCSIM.
But still can't get why it worked. Because I failed to add nuget-pack (VS2015 didn't recognize that) and I didn't add  any references (e.g. s7net.dll).

Mallowan

![solution_tree](https://user-images.githubusercontent.com/37699980/37831016-1b8d6b64-2eb5-11e8-838e-cccd65a856eb.jpg)

**Comment by rapha-dev** [comment]
It is working because s7netplus uses .Net native functions only, like functions defined in System and System.Net. So you don't need to reference any other dll or uncommon namespace.

You may have a look into "References" above the highlighted files in your screenshot.

NuGet adds precompiled dlls to your VS project for convenience.
