### ISSUE TITLE
ErrorCode.ReadData never returned

### ISSUE THREAD

**Issue by arkypita** [killnine/s7netplus#124]
Hi
I see that calling a plc.Read(...) will set a lasterror of "ErrorCode.WriteData". Should not return ErrorCode.ReadData?

I have search for ErrorCode.ReadData reference in code, seem to be only declared but not used.

Suggest:  ReadBytesWithSingleRequest in PlcSyncronous.cs should set ErrorCode.ReadData, not WriteData

**Comment by rapha-dev** [comment]
Agreed, same should be done in `public async Task<List<DataItem>> ReadMultipleVarsAsync(List<DataItem> dataItems)` and `public void ReadMultipleVars(List<DataItem> dataItems)`.

BTW: Why is it marked as obsolete? In my understanding Sync and Async should be exist both unless it is used internally.

**Comment by mycroes** [comment]
> BTW: Why is it marked as obsolete? In my understanding Sync and Async should be exist both unless it is used internally.

Things that can be done `async` should be done `async`. If a user choses not to use `async`, he should make that decision at the top-most level where he can make the decision. As such it does make sense to obsolete the sync API (even though Microsoft will never do such a thing because of backwards compatibility). Note that it's not my decision though, it was changed in PR #111.

**Comment by mesta1** [comment]
About the Obsolete, I didn't notice that. Can someone remove that please? I don't think we will ever remove the synchronous version. @mycroes @rapha-dev

**Comment by mycroes** [comment]
@mesta1 Will do.

**Comment by mycroes** [comment]
It was actually only there on ReadMultipleVars and in some comments, removed all mentions of obsolete in PR #129.

**Comment by rapha-dev** [comment]
Fixed in #125  and #129, may gets obsolete in #137.
