### ISSUE TITLE
Read real value from PLC

### ISSUE THREAD

**Issue by ramanandmittal** [killnine/s7netplus#35]
Dear team,

We are not able to read real value from this program. Please share help for this.

**Comment by oiisamiio** [comment]
Hi there,

reading real works. Just precision looks dirty...

Whats the problem? You don't wrote additional Informations.

![0001](https://cloud.githubusercontent.com/assets/4339308/12423850/c28a4d10-becd-11e5-8ca0-2f6830d1731d.jpg)
![0002](https://cloud.githubusercontent.com/assets/4339308/12423849/c285cd80-becd-11e5-89bd-47bb10e42424.jpg)
![0003](https://cloud.githubusercontent.com/assets/4339308/12423851/c2944c02-becd-11e5-90f2-4c374a43731a.jpg)

**Comment by catenarysoftware** [comment]
I too have been trying to read real data types. I see in your screen shots you have a Bit.cs class, is this a new class that has not be committed yet to Github?

**Comment by mesta1** [comment]
This is an example on how to write and read REAL values. You can check it on  S7.Net.UnitTest / S7NetTests.cs.
Basically you have to convert the number in dword to write it, then convert to real after read it. S7.Net provides all the extensions you need to do this conversions.

// Reading and writing a double is quite complicated, because it needs to be converted to DWord before the write, 
// then reconvert to double after the read. 
double val = 35.687; 
plc.Write("DB1.DBD40", val.ConvertToUInt()); 
double result = ((uint)plc.Read("DB1.DBD40")).ConvertToDouble(); 
}

**Comment by ramanandmittal** [comment]
Thanks dear We are able to read real values

**Comment by CFish66** [comment]
Hi everybody,

I'm a new in VS and S7.Net, In my case, i got an error when reading Real value.
Below is my code, it cannot use ".ConvertToUInt()". C# display and error. I try to translate
from Chinese to English. It mean 'Double' not included definatiion of ".ConvertTUInt()'.

For write a real value to PLC. My case can write a float value directly to plc and plc value is correct.

private void button2_Click_1(object sender, EventArgs e)
        {
            double val = 35.687;
            uint val_1;
            float aa;


            //val_1 = (double)val.ConverToShort();
            Globals.PLC_Struct[5].plc.Write("DB1.DBD0", val.ConvertToUInt());

            //var converted = Convert.ToUInt32(val);
            //Globals.PLC_Struct[5].plc.Write("DB1.DBD0", (uint)val);

            //float dword = Convert.ToSingle( Globals.PLC_Struct[5].plc.Read("DB1.DBD0"));
            //double result = Convert.ToDouble(dword); ;
        }

**Comment by CFish66** [comment]
Does someone can help in reading real value ?
