### ISSUE TITLE
Received bytes and expected bytes unmatching problem

### ISSUE THREAD

**Issue by ErenKaymakci** [killnine/s7netplus#549]
When I try to read two bytes which is INT in DataBlock:
            `byte[] Data = PlcComm.ReadBytes(DataType.DataBlock, 1001, 0, 2);`
error has occured like in below:
_S7.Net.PlcException: 'Received 12 bytes: '32-02-00-00-00-00-00-00-00-00-81-04', expected 20 bytes.'_

I have red all errors that people get same with me and checked the followings in my system:

- Tick "Permit access PUT/GET communication... "
- From Via Portal, Download to device --> Hardware configuration 
- Optimized block access disabled

I even tried downgrade my library version to 0.4.0 because someone says It works in this version, but it didn't work. Can someone help me on this topic? 

Another point: when I call  `ReadStatus()` function It returns 8. I couldn't make sense of it. What Does 8 means?

**Comment by mycroes** [comment]
Hi @ErenKaymakci,

I might be wrong, but I think the `(0x)81` indicates the error class as application/relationship error. I guess you might be using incorrect parameters in the connection setup (wrong rack/slot or TSAP).

With regards to `ReadStatus()`: [8 indicates the PLC is in run status](https://github.com/S7NetPlus/s7netplus/blob/ab6308eacd553f571e4792c6ca31bbbfde5c133c/S7.Net/PlcSynchronous.cs#L520). Values other than 8 depend on the PLC type, that's why this method returns a byte.

**Comment by ErenKaymakci** [comment]
I realized that “Permit access with PUT/GET" is unticked, that was the reason of I can not read/write anything. Thanks for your quick response.
